version: '3.8'

services:
  backend:
    image: node:18-alpine
    working_dir: /app
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - sessions_data:/app/data
    networks:
      - wegetnet
    ports:
      - "8081:8081"
    command: >
      sh -c "
        echo 'Baixando código do GitHub...' &&
        apk add --no-cache git &&
        git clone https://github.com/gabossantos-droid/astromental.git /tmp/repo &&
        cp -r /tmp/repo/backend/* /app/ &&
        echo 'Instalando dependências...' &&
        npm install &&
        echo 'Iniciando servidor...' &&
        node server.js
      "
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: nginx:alpine
    networks:
      - wegetnet
    volumes:
      - frontend_data:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    command: >
      sh -c "
        echo 'Baixando código do GitHub...' &&
        apk add --no-cache git nodejs npm &&
        git clone https://github.com/gabossantos-droid/astromental.git /tmp/repo &&
        cd /tmp/repo/frontend &&
        echo 'Instalando dependências...' &&
        npm install &&
        echo 'Fazendo build...' &&
        npm run build &&
        echo 'Copiando arquivos...' &&
        cp -r build/* /usr/share/nginx/html/ &&
        echo 'Configurando nginx...' &&
        cp nginx.conf /etc/nginx/conf.d/default.conf &&
        echo 'Gerando certificados SSL...' &&
        mkdir -p /etc/ssl/certs &&
        openssl req -x509 -newkey rsa:4096 -keyout /etc/ssl/certs/key.pem -out /etc/ssl/certs/cert.pem -days 365 -nodes -subj '/C=BR/ST=Estado/L=Cidade/O=Organizacao/CN=app.saudemental.icu' &&
        echo 'Iniciando nginx...' &&
        nginx -g 'daemon off;'
      "
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  sessions_data:
    driver: local
  frontend_data:
    driver: local

networks:
  wegetnet:
    external: true
